version: "3.8"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:1.3.1
    ports:
      - "4566:4566"
      - "4569:4569"
    environment:
      - SERVICES=kms,sns,dynamodb,sqs
      - HOSTNAME_EXTERNAL=localhost
      - DEBUG=0
      - KMS_PROVIDER=local-kms
      - AWS_ACCESS_KEY_ID=na
      - AWS_SECRET_ACCESS_KEY=na
      - MY_ONE_LOGIN_USER_ID=${MY_ONE_LOGIN_USER_ID}
    volumes:
      - ./seed.yaml:/init/seed.yaml
      - ./localstack/provision.sh:/etc/localstack/init/ready.d/init-aws.sh

  account-management-frontend:
    container_name: account-management-frontend
    build:
      context: .
      dockerfile: local.Dockerfile
    ports:
      - "6001:6001"
      - "9240:9230"
      - "9229:9229"
    volumes:
      - ./:/app
    environment:
      - AUTH_FRONTEND_URL=${AUTH_FRONTEND_URL}
      - API_BASE_URL=${API_BASE_URL}
      - BASE_URL=${BASE_URL}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SCOPES=${OIDC_CLIENT_SCOPES}
      - AM_API_BASE_URL=${AM_API_BASE_URL}
      - AM_YOUR_ACCOUNT_URL=${AM_YOUR_ACCOUNT_URL}
      - SESSION_EXPIRY=${SESSION_EXPIRY}
      - SESSION_SECRET=${SESSION_SECRET}
      - GOV_ACCOUNTS_PUBLISHING_API_URL=${GOV_ACCOUNTS_PUBLISHING_API_URL}
      - GOV_ACCOUNTS_PUBLISHING_API_TOKEN=${GOV_ACCOUNTS_PUBLISHING_API_TOKEN}
      - ANALYTICS_COOKIE_DOMAIN=${ANALYTICS_COOKIE_DOMAIN}
      - GTM_ID=${GTM_ID}
      - DELETE_TOPIC_ARN=${DELETE_TOPIC_ARN}
      - SUPPORT_LANGUAGE_CY=${SUPPORT_LANGUAGE_CY}
      - SERVICE_STORE_TABLE_NAME=${SERVICE_STORE_TABLE_NAME}
      - ACTIVITY_LOG_STORE_TABLE_NAME=${ACTIVITY_LOG_STORE_TABLE_NAME}
      - SESSION_STORE_TABLE_NAME=${SESSION_STORE_TABLE_NAME}
      - SUPPORT_ACTIVITY_LOG=${SUPPORT_ACTIVITY_LOG}
      - DEBUG=express-session
      - LOCALSTACK_HOSTNAME=localstack
      - AWS_REGION=eu-west-2
      - AUDIT_QUEUE_URL=http://localstack:4566/audit-events
      - GENERATOR_KEY_ARN=${GENERATOR_KEY_ARN}
      - WRAPPING_KEY_ARN=${WRAPPING_KEY_ARN}
      - ACCOUNT_ID={ACCOUNT_ID}
      - ENVIRONMENT=${ENVIRONMENT}
      - VERIFY_ACCESS_VALUE=${VERIFY_ACCESS_VALUE}
    restart: on-failure
    depends_on:
      localstack:
        condition: service_healthy
