version: '3.8'

services:
  localstack:
    image: localstack/localstack:0.12.15
    ports:
      - 4566:4566
    environment:
      - SERVICES=kms
      - HOSTNAME_EXTERNAL=localhost
      - DEFAULT_REGION=eu-west-2
      - DEBUG=1
    volumes:
      - ./seed.yaml:/init/seed.yaml

  redis:
    image: redis:6.0.5-alpine
    ports:
      - 6379:6379

  di-auth-account-management-frontend:
    build: .
    ports:
      - 6001:6001
      - 9240:9230
    volumes:
      - ./:/app
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - AUTH_FRONTEND_URL=${AUTH_FRONTEND_URL}
      - API_BASE_URL=${API_BASE_URL}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SCOPES=${OIDC_CLIENT_SCOPES}
      - AM_API_BASE_URL=${AM_API_BASE_URL}
      - AM_YOUR_ACCOUNT_URL=${AM_YOUR_ACCOUNT_URL}
      - SESSION_EXPIRY=${SESSION_EXPIRY}
      - SESSION_SECRET=${SESSION_SECRET}
      - GOV_ACCOUNTS_PUBLISHING_API_URL=${GOV_ACCOUNTS_PUBLISHING_API_URL}
      - GOV_ACCOUNTS_PUBLISHING_API_TOKEN=${GOV_ACCOUNTS_PUBLISHING_API_TOKEN}
      - ANALYTICS_COOKIE_DOMAIN=${ANALYTICS_COOKIE_DOMAIN}
      - COOKIES_AND_FEEDBACK_URL=${COOKIES_AND_FEEDBACK_URL}
      - GTM_ID=${GTM_ID}
    restart: on-failure