version: "3.8"

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack:1.2.0
    ports:
      - 4566:4566
    environment:
      - SERVICES=kms,sns
      - HOSTNAME_EXTERNAL=localhost
      - DEFAULT_REGION=eu-west-2
      - DEBUG=1
      - KMS_PROVIDER=local-kms
    volumes:
      - ./seed.yaml:/init/seed.yaml
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"

  redis:
    image: redis:6.0.5-alpine
    ports:
      - 6379:6379

  di-auth-account-management-frontend:
    container_name: di-auth-account-management-frontend-dev
    build:
      context: .
      dockerfile: local.Dockerfile
    ports:
      - 6001:6001
      - 9240:9230
      - 9229:9229
    volumes:
      - ./:/app
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - AUTH_FRONTEND_URL=${AUTH_FRONTEND_URL}
      - API_BASE_URL=${API_BASE_URL}
      - BASE_URL=${BASE_URL}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SCOPES=${OIDC_CLIENT_SCOPES}
      - AM_API_BASE_URL=${AM_API_BASE_URL}
      - AM_YOUR_ACCOUNT_URL=${AM_YOUR_ACCOUNT_URL}
      - SESSION_EXPIRY=${SESSION_EXPIRY}
      - SESSION_SECRET=${SESSION_SECRET}
      - GOV_ACCOUNTS_PUBLISHING_API_URL=${GOV_ACCOUNTS_PUBLISHING_API_URL}
      - GOV_ACCOUNTS_PUBLISHING_API_TOKEN=${GOV_ACCOUNTS_PUBLISHING_API_TOKEN}
      - ANALYTICS_COOKIE_DOMAIN=${ANALYTICS_COOKIE_DOMAIN}
      - GTM_ID=${GTM_ID}
      - DELETE_TOPIC_ARN=${DELETE_TOPIC_ARN}
      - SUPPORT_INTERNATIONAL_NUMBERS=${SUPPORT_INTERNATIONAL_NUMBERS}
      - SUPPORT_LANGUAGE_CY=${SUPPORT_LANGUAGE_CY}
      - SUPPORT_NEW_ACCOUNT_HEADER=${SUPPORT_NEW_ACCOUNT_HEADER}
      - SUPPORT_DELETE_SERVICE_STORE=${SUPPORT_DELETE_SERVICE_STORE}
    restart: on-failure
