platform: linux
image_resource:
  type: registry-image
  source:
    repository: hashicorp/terraform
    tag: 1.0.4
    username: ((docker-hub-username))
    password: ((docker-hub-password))    
params:
  DEPLOYER_ROLE_ARN: ((deployer-role-arn-non-prod))
  DNS_DEPLOYER_ROLE_ARN: ((deployer-role-arn-production))
  DNS_STATE_BUCKET: ((dns-state-bucket))
  DNS_STATE_KEY: ((dns-state-key))
  STATE_BUCKET: digital-identity-dev-tfstate
  DEPLOY_ENVIRONMENT: build
  GTM_ID: ((build-gtm-id))
  PUBLISHING_API_URL: ((build-gov-accounts-api-url))
  PUBLISHING_API_URL_TOKEN: ((build-gov-accounts-api-token))
  SESSION_EXPIRY: ((build-session-expiry))
  COOKIES_AND_FEEDBACK_URL: ((build-cookies-and-feedback-url))
  LOGGING_ENDPOINT_ARN: "arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prod"
  LOGGING_ENDPOINT_ENABLED: "true"
  DEPLOY_LISTENER: "true"

inputs:
  - name: account-management-src
  - name: account-management-image
outputs:
  - name: terraform-outputs
run:
  path: /bin/sh
  args:
    - -euc
    - |
      export ACCOUNT_MANAGEMENT_IMAGE_URI=$(cat account-management-image/repository)
      export ACCOUNT_MANAGEMENT_IMAGE_TAG=$(cat account-management-image/tag)
      export ACCOUNT_MANAGEMENT_IMAGE_DIGEST=$(cat account-management-image/digest)
           
      cd "account-management-src/ci/terraform/"
      terraform init -input=false \
        -backend-config "role_arn=${DEPLOYER_ROLE_ARN}" \
        -backend-config "bucket=${STATE_BUCKET}" \
        -backend-config "key=acct-mgmt-${DEPLOY_ENVIRONMENT}-terraform.tfstate" \
        -backend-config "encrypt=true" \
        -backend-config "region=eu-west-2"

      terraform apply -auto-approve \
        -var "deployer_role_arn=${DEPLOYER_ROLE_ARN}" \
        -var "dns_state_bucket=${DNS_STATE_BUCKET}" \
        -var "dns_state_key=${DNS_STATE_KEY}" \
        -var "dns_state_role=${DNS_DEPLOYER_ROLE_ARN}" \
        -var "session_expiry=${SESSION_EXPIRY}" \
        -var "gtm_id=${GTM_ID}" \
        -var "gov_accounts_publishing_api_url=${PUBLISHING_API_URL}" \
        -var "gov_account_publishing_api_token=${PUBLISHING_API_URL_TOKEN}" \
        -var "cookies_and_feedback_url=${COOKIES_AND_FEEDBACK_URL}" \
        -var "logging_endpoint_arn=${LOGGING_ENDPOINT_ARN}" \
        -var "logging_endpoint_enabled=${LOGGING_ENDPOINT_ENABLED}" \
        -var "account_management_image_uri=${ACCOUNT_MANAGEMENT_IMAGE_URI}" \
        -var "account_management_image_digest=${ACCOUNT_MANAGEMENT_IMAGE_DIGEST}" \
        -var "account_management_image_tag=${ACCOUNT_MANAGEMENT_IMAGE_TAG}" \
        -var-file ${DEPLOY_ENVIRONMENT}.tfvars \
      
      terraform output --json > ../../../terraform-outputs/${DEPLOY_ENVIRONMENT}-terraform-outputs.json
