platform: linux
image_resource:
  type: registry-image
  source:
    repository: governmentpaas/awscli
    tag: "469ceea7a619b0abdd6cb27efd4d3bd5e9be3ddb"  # pragma: allowlist secret
    username: ((docker-hub-username))
    password: ((docker-hub-password))
inputs:
  - name: domain-terraform-outputs
  - name: terraform-outputs
outputs:
  - name: di-account-management-deploy-variables
params:
  SESSION_EXPIRY: ((build-session-expiry))
  SESSION_SECRET: ((build-session-secret))
  GTM_ID: ((build-gtm-id))
  PUBLISHING_API_URL: ((build-gov-accounts-api-url))
  PUBLISHING_API_URL_TOKEN: ((build-gov-accounts-api-token))
  COOKIES_AND_FEEDBACK_URL: ((build-cookies-and-feedback-url))
  ENVIRONMENT_NAME: build
  APP_INSTANCES: 1
run:
  path: /bin/sh
  args:
    - -c
    - |
      set -eu
      echo "Generating vars file..."
      API_URL="https://$(jq -r .${ENVIRONMENT_NAME}_api_url.value < domain-terraform-outputs/domain-terraform-outputs.json)"
      AUTH_FRONTEND_URL="$(jq -r .${ENVIRONMENT_NAME}_frontend_url.value < domain-terraform-outputs/domain-terraform-outputs.json)"
      AM_URL="$(jq -r .${ENVIRONMENT_NAME}_account_management_url.value < domain-terraform-outputs/domain-terraform-outputs.json)"
      AM_API_URL="https://$(jq -r .${ENVIRONMENT_NAME}_account_management_api_url.value < domain-terraform-outputs/domain-terraform-outputs.json)"
      AM_YOUR_ACCOUNT_URL="$(jq -r .account_management_your_account_url.value < terraform-outputs/${ENVIRONMENT_NAME}-terraform-outputs.json)"
      ANALYTICS_COOKIE_DOMAIN="$(jq -r .${ENVIRONMENT_NAME}_service_domain.value < domain-terraform-outputs/domain-terraform-outputs.json)"

      cat <<EOF > di-account-management-deploy-variables/vars.yml
      api_base_url: ${API_URL}
      am_api_base_url: ${AM_API_URL}
      analytics_cookie_domain: ${ANALYTICS_COOKIE_DOMAIN}
      session_expiry: ${SESSION_EXPIRY}
      session_secret: ${SESSION_SECRET}
      route_name: ${AM_URL}
      environment_name: ${ENVIRONMENT_NAME}
      am_your_account_url: ${AM_YOUR_ACCOUNT_URL}
      gtm_id: ${GTM_ID}
      publishing_api_url: ${PUBLISHING_API_URL}
      publishing_api_token: ${PUBLISHING_API_URL_TOKEN}
      app_instances: ${APP_INSTANCES}
      auth_frontend_url: ${AUTH_FRONTEND_URL}
      analytics_cookie_domain: ${ANALYTICS_COOKIE_DOMAIN}
      cookies_and_feedback_url: ${COOKIES_AND_FEEDBACK_URL}
      EOF
