version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "account-management-frontend"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-7d9zueiu0w51"
s3_prefix = "account-management-frontend"
parameter_overrides = "VpcStackName=\"vpc-enhanced\" PermissionsBoundary=\"none\" Environment=\"build\" IncomingTrafficCIDRBlocks=\"0.0.0.0/0\""
