---
name: "Build & Test Application"

# Triggered when:
#   - a file, listed below, is pushed to any branch other than `main`, i.e. a feature branch.
#   - invoked by another workflow.
on:
  push:
    paths:
      - "src/**"
      - "test/**"
      - "@types/**"
      - "package.json"
      - "yarn.lock"
      - "tsconfig.json"
      - ".github/workflows/build-test-application.yml"
    branches-ignore:
      - main
  workflow_call:
    inputs:
      gitRef:
        required: false
        type: string
        default: ${{ github.ref }}

jobs:
  build_test_application:
    name: "Build & Test Application"
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack:1.3.1
        env:
          SERVICES: kms,sns,dynamodb
          HOSTNAME_EXTERNAL: localstack
          AWS_DEFAULT_REGION: eu-west-2
          AWS_ACCESS_KEY_ID: na
          AWS_SECRET_ACCESS_KEY: na
          DEBUG: 0
        ports:
          - 4566:4566
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.gitRef || github.ref }}

      - name: Provision localstack
        env:
          AWS_DEFAULT_REGION: eu-west-2
          AWS_ACCESS_KEY_ID: na
          AWS_SECRET_ACCESS_KEY: na
        run:
          ./localstack/provision.sh

        shell: bash

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.0

      - name: Install dependencies defined in yarn.lock
        run: yarn install --frozen-lockfile

      - name: Build app
        run: yarn build

      - name: Run unit tests
        run: yarn test:unit

      - name: Run integration tests
        run: yarn test:integration

      - name: Run lint
        run: yarn lint
    env:
      API_BASE_URL: http://localhost:6000/api
      AM_API_BASE_URL: http://localhost:5000/api
      SUPPORT_INTERNATIONAL_NUMBERS: 1
      GOV_ACCOUNTS_PUBLISHING_API_URL: http://localhost:1000/api
      GOV_ACCOUNTS_PUBLISHING_API_TOKEN: token
      AM_YOUR_ACCOUNT_URL: some url
      OIDC_CLIENT_ID: test
      OIDC_CLIENT_SCOPES: openid
      SESSION_SECRET: secret
      SESSION_EXPIRY: 3600000
      SESSION_STORE_TABLE_NAME: account-mgmt-frontend-SessionStore

  code_analysis:
    runs-on: ubuntu-latest
    name: "Code Analysis"
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.gitRef || github.ref }}

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
