name: Check Translations

# Trigger only when changes occur in the locales directory in a PR
on:
  pull_request:
    paths:
      - 'src/locales/**'  

jobs:
  check_translation:
    name: "Check locale language changes"
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # pin@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Validate Translation Files
        run: |
          files_changed="${{ steps.changed-files.outputs.files }}"
          if echo "$files_changed" | grep -q "^src/locales/en/translation.json" && echo "$files_changed" | grep -q "^src/locales/cy/translation.json"; then
            echo "Both translation files have changed."
          else
            echo "Only one of the translation files has changed or neither has changed."
            exit 1
          fi
