name: Check Translations

# Triggered when:
# - a change in either the en or cy locale translation json is pushed to main without changing the other locale.
on:
  push:
    branches:
      - main 
  workflow_call:
    inputs:
      gitRef:
        required: false
        type: string
        default: ${{ github.ref }}

jobs:
  check_translation:
    name: "Check locale language changes"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        with:
          ref: ${{ inputs.gitRef || github.ref }}

      - name: Check translations
        run: |
          changed_en=$(git diff --name-only ${{ github.base_ref }}...${{ github.sha }} | grep '^src/locales/en/translation.json$' || true)
          changed_cy=$(git diff --name-only ${{ github.base_ref }}...${{ github.sha }} | grep '^src/locales/cy/translation.json$' || true)

          if [[ -n "$changed_en" && -z "$changed_cy" ]]; then
            echo "Error: Changes to 'src/locales/en/translation.json' detected without corresponding changes to 'src/locales/cy/translation.json'"
            exit 1
          elif [[ -z "$changed_en" && -n "$changed_cy" ]]; then
            echo "Error: Changes to 'src/locales/cy/translation.json' detected without corresponding changes to 'src/locales/en/translation.json'"
            exit 1
          fi
