name: Check Translations

# Triggered when:
# - a PR to any branch has changes in the locales path.
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'src/locales/'

jobs:
  check_translation:
    name: "Check locale language changes"
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Determine File Changes
        id: file_changes
        run: |
          # Get list of files changed in the PR
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})"

      - name: Validate Translation Files
        run: |
          files_changed="${{ steps.file_changes.outputs.files }}"
          if (echo "$files_changed" | grep -q "^src/locales/en/translation.json") && (echo "$files_changed" | grep -q "^src/locales/cy/translation.json"); then
            echo "Both translation files have changed."
          else
            echo "Only one of the translation files has changed or neither has changed."
            exit 1
          fi