name: Check Translations

on:
  pull_request:
    paths:
      - 'src/locales/**'  # Trigger only when changes occur in the locales directory
  workflow_call:
    inputs:
      gitRef:
        required: false
        type: string
        default: ${{ github.ref }}

jobs:
  check_translation:
    name: "Check locale language changes"
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: List changed files
        id: changed-files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} > changed_files.txt

      - name: Validate Translation Files
        run: |
          changed_files=$(cat changed_files.txt)
          if echo "$changed_files" | grep -q "^src/locales/en/translation.json" && echo "$changed_files" | grep -q "^src/locales/cy/translation.json"; then
            echo "Both translation files have changed."
          else
            echo "Only one of the translation files has changed or neither has changed."
            exit 1
          fi
