name: Check Translations

# Trigger only when changes occur in the locales directory in a PR
on:
  pull_request:
    paths:
      - 'src/locales/**'  

jobs:
  check_translation:
    name: "Check locale language changes"
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # pin@v3
        with:
          fetch-depth: 2

      - name: Get changes
        id: changed-files
        run: |
          echo "::set-output name=files::$(git diff --name-only HEAD^1 HEAD)"

      - name: Validate Translation Files
        run: |
          files_changed="${{ steps.changed-files.outputs.files }}"
      
          # Check if en/translation.json is changed
          en_changed=$(echo "$files_changed" | grep -q "^src/locales/en/translation.json" && echo "true" || echo "false")
      
          # Check if cy/translation.json is changed
          cy_changed=$(echo "$files_changed" | grep -q "^src/locales/cy/translation.json" && echo "true" || echo "false")
      
          # Validate based on changes
          if [[ "$en_changed" == "true" && "$cy_changed" == "true" ]]; then
            echo "Both translation files have changed. No action needed."
          elif [[ "$en_changed" == "true" && "$cy_changed" == "false" ]]; then
            echo "Only en/translation.json has changed. Please update cy/translation.json."
            exit 1
          elif [[ "$en_changed" == "false" && "$cy_changed" == "true" ]]; then
            echo "Only cy/translation.json has changed. Please update en/translation.json."
            exit 1
          else
            echo "Neither translation file has changed. No action needed."
          fi
