name: Check Translations

# Triggered when:
# - a change in either the en or cy locale translation json is pushed to main without changing the other locale.
on:
  push:
    branches:
      - '*' 
  workflow_call:
    inputs:
      gitRef:
        required: false
        type: string
        default: ${{ github.ref }}

jobs:
  check_translation:
    name: "Check locale language changes"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        with:
          ref: ${{ github.base_ref }}

      - name: Check translations
        run: |
          # Set paths for translation files
          en_translation_file="src/locales/en/translation.json"
          cy_translation_file="src/locales/cy/translation.json"
          
          # Check if 'en_translation_file' exists
          if [ ! -f "$en_translation_file" ]; then
            echo "Error: 'src/locales/en/translation.json' file not found"
            exit 1
          fi

          # Check if 'cy_translation_file' exists
          if [ ! -f "$cy_translation_file" ]; then
            echo "Error: 'src/locales/cy/translation.json' file not found"
            exit 1
          fi
        
          # Check for changes in translation files
          changed_en=$(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} -- "$en_translation_file")
          changed_cy=$(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} -- "$cy_translation_file")

          # Display error if changes are detected in one file without corresponding changes in the other file
          if [[ -n "$changed_en" && -z "$changed_cy" ]]; then
            echo "Error: Changes to 'src/locales/en/translation.json' detected without corresponding changes to 'src/locales/cy/translation.json'"
            exit 1
          elif [[ -z "$changed_en" && -n "$changed_cy" ]]; then
            echo "Error: Changes to 'src/locales/cy/translation.json' detected without corresponding changes to 'src/locales/en/translation.json'"
            exit 1
          fi
