name: Check Translations

# Triggered when:
# - a change in either the en or cy locale translation json is detected in a PR.
on:
  pull_request:
    branches:
      - '*'

jobs:
  check_translation:
    name: "Check locale language changes"
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check file locations exist
        run: |
          # Set paths for translation files
          en_translation_file="src/locales/en/translation.json"
          cy_translation_file="src/locales/cy/translation.json"

          # Check if 'en_translation_file' exists and has changes
          if [ -f "$en_translation_file" ]; then
            changed_en=$(git diff --name-only "${{ github.base_ref }}..${{ github.sha }}" -- "$en_translation_file")
          else
            echo "EN Path not found"
            changed_en=""
          fi

          # Check if 'cy_translation_file' exists and has changes
          if [ -f "$cy_translation_file" ]; then
            changed_cy=$(git diff --name-only "${{ github.base_ref }}..${{ github.sha }}" -- "$cy_translation_file")
          else
            echo "CY Path not found"
            changed_cy=""
          fi

      - name: Check changes to locale files
        run: |
          # Check if changes are detected in one locale without corresponding changes in the other
          if [[ -n "$changed_en" && -z "$changed_cy" ]]; then
            echo "Error: Changes to 'src/locales/en/translation.json' detected without corresponding changes to 'src/locales/cy/translation.json'"
            exit 1
          elif [[ -n "$changed_cy" && -z "$changed_en" ]]; then
            echo "Error: Changes to 'src/locales/cy/translation.json' detected without corresponding changes to 'src/locales/en/translation.json'"
            exit 1