name: Check Translations

# Triggered when:
# - a change in either the en or cy locale translation json is detected in a PR.
on:
  pull_request:
    branches:
      - '*'

jobs:
  check_translation:
    name: "Check locale language changes"
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # pin@v3
        with:
          ref: ${{ inputs.gitRef || github.ref }}

      - name: Check translations
        run: |
          # Set paths for translation files
          en_translation_file="src/locales/en/translation.json"
          cy_translation_file="src/locales/cy/translation.json"

          # Check if 'en_translation_file' exists and has changes
          if [ -f "$en_translation_file" ]; then
            changed_en=$(git diff --name-only HEAD^ -- "$en_translation_file")
          else
            changed_en=""
          fi

          # Check if 'cy_translation_file' exists and has changes
          if [ -f "$cy_translation_file" ]; then
            changed_cy=$(git diff --name-only HEAD^ -- "$cy_translation_file")
          else
            changed_cy=""
          fi

          # Check if changes are detected in one locale without corresponding changes in the other
          if [[ -n "$changed_en" && -z "$changed_cy" ]]; then
            echo "Error: Changes to 'src/locales/en/translation.json' detected without corresponding changes to 'src/locales/cy/translation.json'"
            exit 1
          elif [[ -n "$changed_cy" && -z "$changed_en" ]]; then
            echo "Error: Changes to 'src/locales/cy/translation.json' detected without corresponding changes to 'src/locales/en/translation.json'"
            exit 1
          fi