name: Check Translations

# Triggered when:
# - a PR to any branch has changes in the locales path.
on:
  pull_request:
    types: [opened, synchronize]
  workflow_call:
    inputs:
      gitRef:
        required: false
        type: string
        default: ${{ github.ref }}

jobs:
  check_translation:
    name: "Check locale language changes"
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # pin@v3
        with:
          ref: ${{ inputs.gitRef || github.ref }}
      
      - name: List current directory contents
        run: ls -l

      - name: Process files changed in the current commit
        run: |
          changedFiles=$(git diff --name-only HEAD^)
          for file in $changedFiles; do
            echo "Processing file: $file"
          done

      - name: Determine File Changes
        id: file_changes
        run: |
          # Get list of files changed in the PR
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})"

      - name: Validate Translation Files
        run: |
          files_changed="${{ steps.file_changes.outputs.files }}"
          if (echo "$files_changed" | grep -q "^src/locales/en/translation.json") && (echo "$files_changed" | grep -q "^src/locales/cy/translation.json"); then
            echo "Both translation files have changed."
          else
            echo "Only one of the translation files has changed or neither has changed."
            exit 1
          fi