---
name: "Validate & Verify"

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  validate_application:
    name: App Checks
    uses: ./.github/workflows/build-test-application.yml
    secrets: inherit

  validate_container:
    name: Container Checks
    uses: ./.github/workflows/validate-docker-image.yml
    secrets: inherit
    needs: validate_application

  validate_deployment:
    name: Deployment Template Checks
    uses: ./.github/workflows/validate-sam-template.yml
    secrets: inherit
    needs: validate_container
