---
name: "Verify & Publish"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  validate_application:
    name: App Checks
    uses: ./.github/workflows/build-test-application.yml
    secrets: inherit

  validate_container:
    name: Container Checks
    uses: ./.github/workflows/validate-docker-image.yml
    secrets: inherit
    needs: validate_application

  validate_deployment:
    name: Deployment Template Checks
    uses: ./.github/workflows/validate-sam-template.yml
    secrets: inherit
    needs: validate_container

  publish_artifacts:
    name: "Publish Image & Template"
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: validate_deployment
    steps:
      - name: "Push signed image to ECR, updated SAM template wih image then upload it to the S3 Artifact Bucket"
        uses: alphagov/di-devplatform-upload-action-ecr@1.0.2
        with:
          artifact-bucket-name: ${{ secrets.ARTIFACT_SOURCE_BUCKET_NAME }}
          container-sign-kms-key-arn: ${{ secrets.CONTAINER_SIGN_KMS_KEY }}
          working-directory: .
          template-file: deploy/template.yaml
          role-to-assume-arn: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          ecr-repo-name: ${{ secrets.ECR_REPOSITORY }}

      - name: "Delegated Deployment via AWS CodeDeploy"
        run: echo "Deployment has been delegated to AWS CodeDeploy"
